# Generated by Django 3.1.7 on 2021-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affilliatecode',
            field=models.CharField(default='tpglobalfx', max_length=200),
        ),
    ]
