# Generated by Django 3.1.7 on 2021-03-17 12:50

from django.db import migrations, models
import investment.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20210317_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affilliatecode',
            field=models.CharField(default=investment.models.UserProfile.tpdefault, max_length=200),
        ),
    ]
