# Generated by Django 3.1.7 on 2021-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20210317_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passcode',
            field=models.CharField(default='formaluser', max_length=100),
            preserve_default=False,
        ),
    ]
