# Generated by Django 3.1.7 on 2021-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_userprofile_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
